[project]
name = "tonyenc-decrypter"
version = "0.1.0"
description = "A command-line tool for decrypting PHP files that have been encrypted with tonyenc"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["click>=8.1.8", "rich>=14.0.0"]
